# Generated by Django 5.1.2 on 2024-10-26 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('707b0d7a-d34a-40f9-8011-b9a91c966f10'), editable=False, primary_key=True, serialize=False),
        ),
    ]
