# Generated by Django 5.1.2 on 2024-10-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6e10c91-b504-4d33-97a3-5fd836c4049b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
