# Generated by Django 5.1.2 on 2024-10-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subintent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
