# Generated by Django 5.1.2 on 2024-10-26 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_password_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42e06e5c-e2c1-4adf-87b4-46f64132efb2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
